<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateDocumentDefinitionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('document_definitions', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->timestamps();
            $table->string('name', 25);
            $table->string('title', 25);
            $table->string('description', 256);
            $table->unsignedBigInteger('document_type_id')->nullable();
            $table->foreign('document_type_id')->references('id')->on('dict_document_types');
            $table->unsignedBigInteger('domain_id')->nullable();
            $table->foreign('domain_id')->references('id')->on('domains');
            $table->bigInteger('form_id')->unsigned();
            $table->foreign('form_id')->references('id')->on('forms');
            $table->bigInteger('template_id')->unsigned();
            $table->foreign('template_id')->references('id')->on('templates');
            $table->integer('general_domain_storage')->unsigned();
            $table->text('form_content')->nullable();
            $table->text('template_content')->nullable();
            $table->string('document_domain', 25);
            $table->string('required_fields', 500)->nullable();
            $table->unsignedBigInteger('secrecy_degree_id')->nullable();
            $table->foreign('secrecy_degree_id')->references('id')->on('dict_secrecy_degrees');
            $table->string('secrecy_clause', 10)->nullable();
            $table->text('report_content')->nullable();
            $table->string('paper_case_generator', 80)->nullable();
            $table->text('autogenerated_fields')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('document_definitions');
    }
}
